---

- name: Kafka configuration
  copy:
    content: |
      broker.id={{ kafka_broker_id }}
      log.dirs=/var/log/kafka
      zookeeper.connect={{ groups['zookeepers'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(':2181,') }}:2181
      listeners=PLAINTEXT://{{ ansible_default_ipv4.address }}:9092
      replica.fetch.max.bytes=104857600
      message.max.bytes=104857600
      compression.type=producer
      num.partitions=1
      log.retention.hours=48
      log.retention.check.interval.ms=300000
      unclean.leader.election.enable=false
      broker.id.generation.enable=false
      auto.create.topics.enable=false
    dest: /etc/kafka/server.properties
  notify: Restart Kafka

- name: Create Kafka SystemD unit configuration
  copy:
    content: |
      [Unit]
        Description=Kafka Service
        Requires=zookeeper.service
        After=zookeeper.service

      [Service]
        User=kafka
        ExecStart=/usr/lib/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties

      [Install]
        WantedBy=default.target
    dest: /etc/systemd/system/kafka.service
  notify: Restart Kafka

- name: Enable Kafka Service
  service:
    name: "kafka"
    enabled: yes
    state: started
